# Generated by Django 4.2.6 on 2023-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count_product', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
